version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./alidev.conf:/etc/nginx/conf.d/alidev.conf
      - ./n8n.conf:/etc/nginx/conf.d/n8n.conf
      - ./artinmusik.conf:/etc/nginx/conf.d/artin.conf
      - ./ai.conf:/etc/nginx/conf.d/ai.conf
      - ./artindevmarket.conf:/etc/nginx/conf.d/artindevmarket.conf
      - ./woodentoy.conf:/etc/nginx/conf.d/woodentoys.conf
      - ./alidev:/usr/share/nginx/html/alidev
      - ./artinmusik:/usr/share/nginx/html/artin
      - ./ai:/usr/share/nginx/html/ai
      - ./artindevmarket:/usr/share/nginx/html/artindevmarket
      - ./woodentoys:/usr/share/nginx/html/woodentoys
    depends_on:
      - woodentoys
      - n8n
    networks:
      - my_network

  db:
    image: mariadb:10.4
    container_name: db
    platform: linux/arm64
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz!QAZ
      MYSQL_USER: user_woodentoys
      MYSQL_PASSWORD: 1qaz!QAZ
      MYSQL_DATABASE: woodentoys
    volumes:
      - ./backup:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1qaz!QAZ"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - my_network

  woodentoys:
    image: wordpress:php7.4-fpm
    platform: linux/arm64
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user_woodentoys
      WORDPRESS_DB_PASSWORD: 1qaz!QAZ
      WORDPRESS_DB_NAME: woodentoys
    volumes:
      - ./woodentoys:/usr/share/nginx/html/woodentoys
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network
n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yourStrongPasswordHere
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=http://n8n.artindevmarket.com/
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - my_network

volumes:
  n8n_data:

networks:
  my_network:

