version: '3'
services:
  alidev:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/usr/share/nginx/html
      - ./alidev.conf:/etc/nginx/conf.d/alidev.conf
      - ./artinmusik.conf:/etc/nginx/conf.d/artin.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on:
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
  dbdata:
