version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8081:80"
      - "8082:80"
      - "8083:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./alidev:/usr/share/nginx/html/alidev
      - ./artinmusik:/usr/share/nginx/html/artinmusik
      - ./woodentoys:/usr/share/nginx/html/woodentoys
    networks:
      - my_network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: woodentoys
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - ./woodentoys.sql:/docker-entrypoint-initdb.d/woodentoys.sql
    networks:
      - my_network

  woodentoys_wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=
      - WORDPRESS_DB_NAME=woodentoys
    volumes:
      - ./woodentoys:/var/www/html
      - ./woodentoy.conf:/etc/nginx/conf.d/woodentoy.conf
    networks:
      - my_network

networks:
  my_network:
