version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:80
      - 8081:80
      - 8082:80
    volumes:
      - ./:/usr/share/nginx/html
      - ./alidev.conf:/etc/nginx/conf.d/alidev.conf
      - ./artinmusik.conf:/etc/nginx/conf.d/artin.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - my_network
  
  alidev:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./alidev:/usr/share/nginx/html
    networks:
      - my_network

  artinmusik:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./artinmusik:/usr/share/nginx/html
    networks:
      - my_network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: woodentoys
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - ./woodentoys.sql:/docker-entrypoint-initdb.d/woodentoys.sql

  woodentoys:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    ports:
      - 8081:80
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=
      - WORDPRESS_DB_NAME=woodentoys
    volumes:
      - wordpress:/var/www/html
    networks:
      - my_network

networks:
  my_network:
