version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - ./alidev.conf:/etc/nginx/conf.d/alidev.conf
      - ./artinmusik.conf:/etc/nginx/conf.d/artin.conf
      - ./ai.conf:/etc/nginx/conf.d/ai.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./alidev:/usr/share/nginx/html/alidev
      - ./artinmusik:/usr/share/nginx/html/artin
      - ./ai:/usr/share/nginx/html/ai
    networks:
      - my_network

  db:
    image: mariadb:10.4
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: woodentoys
    # volumes:
    #   - ./data:/var/lib/mysql
    networks:
      - my_network

  woodentoys:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    ports:
      - 80:80
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./woodentoys:/var/www/html/woodentoys
      - ./woodentoy.conf:/etc/nginx/conf.d/woodentoy.conf
    networks:
      - my_network

networks:
  my_network:
